#!/usr/bin/env ruby

raise "Must run as root" unless Process.uid == 0

if ((%w[start stop restart].include? ARGV[0]) && ARGV[1].to_s != "" && ARGV[2].to_s != "") || %w[stop restart].include?(ARGV[0])
  ARGV[3] ||= 'development'
  system "ruby script/runner script/tcpdump.rb #{ARGV[0]} #{ARGV[1]} #{ARGV[2]} -e #{ARGV[3]}&"
else
  puts "Usage:\n\truby script/runner script/tcp_dumper start|stop|restart iface logfile [ENVIROMENT]"
end
